const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CATS={expense:['餐饮','交通','购物','居住','娱乐','医疗','教育','人情','其他'],income:['工资','奖金','理财','退款','兼职','其他']};
const ICONS={'餐饮':'餐','交通':'行','购物':'购','居住':'家','娱乐':'乐','医疗':'医','教育':'学','人情':'礼','工资':'薪','奖金':'奖','理财':'财','退款':'退','兼职':'职','其他':'·'};
const COLORS=['#e98545','#79a995','#e2b657','#6d8fb2','#c27f86','#856da5','#71a6a2','#b99573','#a5aaa4'];
let records=JSON.parse(localStorage.getItem('qinghe-records')||'[]'),entryType='expense',period='month',deferredPrompt;
const money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const localInput=d=>{d=new Date(d);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
function save(){localStorage.setItem('qinghe-records',JSON.stringify(records));render()}
function samePeriod(date,p){const d=new Date(date),n=new Date();if(p==='day')return d.toDateString()===n.toDateString();if(p==='week'){const start=new Date(n);start.setHours(0,0,0,0);start.setDate(n.getDate()-((n.getDay()+6)%7));return d>=start&&d<new Date(start.getTime()+604800000)}return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()}
function row(r){return `<div class="transaction"><div class="cat-icon">${ICONS[r.category]||'·'}</div><div><h3>${escapeHtml(r.note||r.category)}</h3><p>${r.category} · ${new Date(r.date).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</p></div><span class="amount ${r.type}">${r.type==='income'?'+':'-'}${money(r.amount)}</span></div>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function render(){const month=records.filter(r=>samePeriod(r.date,'month')),inc=month.filter(r=>r.type==='income').reduce((a,r)=>a+r.amount,0),exp=month.filter(r=>r.type==='expense').reduce((a,r)=>a+r.amount,0);$('#monthBalance').textContent=money(inc-exp);$('#monthIncome').textContent=money(inc);$('#monthExpense').textContent=money(exp);const sorted=[...records].sort((a,b)=>new Date(b.date)-new Date(a.date));$('#recentList').innerHTML=sorted.slice(0,5).map(row).join('')||'<div class="empty">还没有记录，记下今天的第一笔吧</div>';$('#allList').innerHTML=sorted.map(row).join('')||'<div class="empty">暂无明细</div>';renderStats()}
function openEntry(scan=false){entryType='expense';updateType();$('#entryForm').reset();$('#date').value=localInput(new Date());$('#dialogEyebrow').textContent=scan?'截图识别':'新增记录';$('#dialogTitle').textContent=scan?'核对识别结果':'记一笔';$('#scanStatus').hidden=!scan;$('#entryDialog').showModal()}
function updateType(){$$('.type-toggle button').forEach(b=>b.classList.toggle('active',b.dataset.type===entryType));$('#category').innerHTML=CATS[entryType].map(c=>`<option>${c}</option>`).join('')}
async function recognize(file){openEntry(true);const status=$('#scanStatus');status.textContent='正在识别截图，请稍候…';if(!window.Tesseract){status.textContent='识别服务暂时不可用，请手动填写截图内容。';return}try{const {data:{text}}=await Tesseract.recognize(file,'chi_sim+eng',{logger:m=>{if(m.status==='recognizing text')status.textContent=`正在识别截图 ${Math.round(m.progress*100)}%`}});const amounts=[...text.matchAll(/(?:¥|￥|CNY|金额|支付|合计)?\s*(-?\d{1,6}(?:\.\d{1,2})?)/gi)].map(x=>Number(x[1])).filter(n=>n>0&&n<1000000);if(amounts.length)$('#amount').value=Math.max(...amounts).toFixed(2);const lines=text.split(/\n/).map(x=>x.trim()).filter(x=>x.length>1);$('#note').value=(lines.find(x=>/店|餐|超市|公司|商行|支付|收款/.test(x))||lines[0]||'').slice(0,40);const rules=[['餐饮',/餐|美团|饿了么|咖啡|奶茶|食品/],['交通',/滴滴|地铁|铁路|打车|公交|加油/],['购物',/淘宝|京东|拼多多|超市|商场/],['居住',/房租|物业|水费|电费|燃气/],['医疗',/医院|药房|诊所/],['娱乐',/电影|游戏|会员/]];const hit=rules.find(x=>x[1].test(text));if(hit)$('#category').value=hit[0];status.textContent=amounts.length?'识别完成，请核对金额和分类后保存。':'未找到明确金额，请手动补充后保存。'}catch(e){status.textContent='识别没有成功，请手动填写截图内容。'}}
function renderStats(){const list=records.filter(r=>r.type==='expense'&&samePeriod(r.date,period));const total=list.reduce((a,r)=>a+r.amount,0);$('#periodExpense').textContent=money(total);$('#periodTitle').textContent={day:'今日支出',week:'本周支出',month:'本月支出'}[period];$('#categoryTotal').textContent=`合计 ${money(total)}`;const groups={};list.forEach(r=>groups[r.category]=(groups[r.category]||0)+r.amount);const entries=Object.entries(groups).sort((a,b)=>b[1]-a[1]);$('#categoryLegend').innerHTML=entries.map(([c,v],i)=>`<div class="legend-row"><i class="dot" style="background:${COLORS[i%COLORS.length]}"></i><span>${c}</span><b>${total?Math.round(v/total*100):0}%</b></div>`).join('')||'<span class="eyebrow">暂无支出数据</span>';drawDonut(entries.map(x=>x[1]),total);drawTrend(list)}
function sizeCanvas(c){const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return [x,r.width,r.height]}
function drawDonut(vals,total){const c=$('#donutChart'),[x,w,h]=sizeCanvas(c),cx=w/2,cy=h/2,r=Math.min(w,h)*.37;x.clearRect(0,0,w,h);if(!total){x.strokeStyle='#e8ece9';x.lineWidth=22;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.stroke();return}let a=-Math.PI/2;vals.forEach((v,i)=>{const e=a+v/total*Math.PI*2;x.strokeStyle=COLORS[i%COLORS.length];x.lineWidth=22;x.beginPath();x.arc(cx,cy,r,a+.025,e-.025);x.stroke();a=e});x.fillStyle='#18342f';x.font='700 13px sans-serif';x.textAlign='center';x.fillText('支出',cx,cy-3);x.font='700 12px sans-serif';x.fillText(money(total),cx,cy+16)}
function drawTrend(list){const c=$('#trendChart'),[x,w,h]=sizeCanvas(c),count=period==='day'?6:period==='week'?7:new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate(),vals=Array(count).fill(0),now=new Date();list.forEach(r=>{const d=new Date(r.date);let i=period==='day'?Math.min(5,Math.floor(d.getHours()/4)):period==='week'?(d.getDay()+6)%7:d.getDate()-1;vals[i]+=r.amount});const max=Math.max(...vals,1),pad=18,base=h-26;x.clearRect(0,0,w,h);x.strokeStyle='#dfe8e4';x.beginPath();x.moveTo(pad,base);x.lineTo(w-pad,base);x.stroke();x.strokeStyle='#e98545';x.lineWidth=3;x.lineJoin='round';x.beginPath();vals.forEach((v,i)=>{const px=pad+i*(w-pad*2)/Math.max(1,count-1),py=base-v/max*(h-48);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#e98545';vals.forEach((v,i)=>{if(v){const px=pad+i*(w-pad*2)/Math.max(1,count-1),py=base-v/max*(h-48);x.beginPath();x.arc(px,py,3,0,Math.PI*2);x.fill()}})}
$('#manualBtn').onclick=()=>openEntry(false);$('#scanBtn').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>{if(e.target.files[0])recognize(e.target.files[0]);e.target.value=''};$$('.type-toggle button').forEach(b=>b.onclick=()=>{entryType=b.dataset.type;updateType()});$('#entryForm').addEventListener('submit',e=>{e.preventDefault();const amount=Number($('#amount').value);if(!amount||amount<=0)return toast('请输入正确金额');records.push({id:crypto.randomUUID?.()||Date.now(),type:entryType,amount,category:$('#category').value,note:$('#note').value.trim(),date:new Date($('#date').value).toISOString()});save();$('#entryDialog').close();toast('已保存')});
function go(page){$$('.page').forEach(p=>p.classList.toggle('active',p.id===page+'Page'));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='stats')setTimeout(renderStats)}$$('.bottom-nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('#periodTabs button').forEach(b=>b.onclick=()=>{period=b.dataset.period;$$('#periodTabs button').forEach(x=>x.classList.toggle('active',x===b));renderStats()});$('#clearBtn').onclick=()=>{if(records.length&&confirm('确定清空全部记账记录吗？此操作无法撤销。')){records=[];save();toast('记录已清空')}};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}else toast('请使用浏览器菜单“添加到主屏幕”')};
$('#todayLabel').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');window.addEventListener('resize',()=>{if($('#statsPage').classList.contains('active'))renderStats()});updateType();render();
